src/Blog.Web/Controllers/TagController.cs
using Blog.Core.Interfaces;
using Blog.Core.Models;
using Blog.Infrastructure.Repositories;
using Blog.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    public class TagController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TagController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var repository = _unitOfWork.GetRepository<Tag>() as TagRepository;
            IEnumerable<Tag> tagList = await repository.GetAllTags();

            return View(tagList.OrderByDescending(x => x.Articles.Count));
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        //Create tag
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(Tag model)
        {
            var repository = await _unitOfWork.GetRepository<Tag>().GetAllAsync();

            if (repository.Any(tag => tag.Title.ToLower() == model.Title.ToLower()))
            {
                ModelState.AddModelError("Title", "Такой тег уже существует");
            }

            if (ModelState.IsValid)
            {
                var tag = new Tag
                {
                    Title = model.Title,
                    Description = model.Description
                };

                await _unitOfWork.GetRepository<Tag>().Create(tag);

                TempData["success"] = "Тег успешно добавлен";

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var tagFromDb = await _unitOfWork.GetRepository<Tag>().GetByIdAsync(id);

            if (tagFromDb == null)
            {
                return NotFound();
            }

            var tagModel = new TagViewModel
            {
                Title = tagFromDb.Title,
                Description = tagFromDb.Description
            };

            return View(tagModel);
        }

        //Edit tag
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(Guid id, TagViewModel model)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var tagFromDb = await _unitOfWork.GetRepository<Tag>().GetByIdAsync(id);

            if (tagFromDb == null)
            {
                return NotFound();
            }

            var repository = await _unitOfWork.GetRepository<Tag>().GetAllAsync();

            if (tagFromDb.Title != model.Title && repository.Any(tag => tag.Title.ToLower() == model.Title.ToLower()))
            {
                ModelState.AddModelError("Title", "Такой тег уже существует");
            }

            if (ModelState.IsValid)
            {
                tagFromDb.Title = model.Title;
                tagFromDb.Description = model.Description;

                await _unitOfWork.GetRepository<Tag>().Update(tagFromDb);

                TempData["success"] = "Тег успешно обновлен";

                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = "Не удалось обновить тег";
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id, string sortOrder)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var repository = _unitOfWork.GetRepository<Tag>() as TagRepository;
            var tagFromDb = await repository.GetTagById(id);

            if (tagFromDb == null)
            {
                return NotFound();
            }

            if (sortOrder == "top_desc")
            {
                tagFromDb.Articles = tagFromDb.Articles.OrderByDescending(s => s.ArticleLikes.Count).ToList();
            }
            else
            {
                tagFromDb.Articles = tagFromDb.Articles.OrderByDescending(s => s.Date).ToList();
            }

            return View(tagFromDb);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var tagFromDb = await _unitOfWork.GetRepository<Tag>().GetByIdAsync(id);

            if (tagFromDb == null)
            {
                return NotFound();
            }

            return View(tagFromDb);
        }

        //Delete tag
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var tagFromDb = await _unitOfWork.GetRepository<Tag>().GetByIdAsync(id);

            if (tagFromDb == null)
            {
                return NotFound();
            }

            var deleteTask = _unitOfWork.GetRepository<Tag>().Delete(tagFromDb);
            await deleteTask;

            if (deleteTask.IsCompletedSuccessfully)
            {
                TempData["success"] = "Тег успешно удален";
            }
            else
            {
                TempData["error"] = "Не удалось удалить тег";
            }

            return RedirectToAction("Index");
        }
    }
}

src/Blog.Web/Controllers/UserController.cs
using Blog.Core.Interfaces;
using Blog.Core.Models;
using Blog.Infrastructure.Repositories;
using Blog.Web.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blog.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(UserManager<ApplicationUser> userManager, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        [Route("Profile/{id}")]
        public async Task<IActionResult> GetUserProfile(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var user = await _userManager.Users.Include(user => user.Articles)
                                               .ThenInclude(article => article.Tags)
                                               .Include(user => user.Comments)
                                               .FirstOrDefaultAsync(user => user.Id == id.ToString());

            if (user == null)
            {
                return NotFound();
            }

            var model = new UserProfileViewModel
            {
                ImagePath = user.ImagePath,
                Name = user.Name,
                Bio = user.Bio,
                Location = user.Location,
                JoinedDate = user.JoinedDate,
                Email = user.Email,
                Website = user.Website,
                Education = user.Education,
                Work = user.Work,
                Learning = user.Learning,
                Skills = user.Skills,
                Comments = user.Comments.Count,
                Articles = user.Articles.OrderByDescending(article => article.Date).ToList()
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetUserReadingList(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var repository = _unitOfWork.GetRepository<Article>() as ArticleRepository;
            var readingList = await repository.GetAllArticles().Where(article => article.Favourites.Any(favourite => favourite.UserId == id)).ToListAsync();
            var tagList = readingList.SelectMany(article => article.Tags).Select(tag => tag.Title).Distinct().ToList();

            var model = new ReadingListViewModel
            {
                UserId = id,
                Articles = readingList,
                Tags = tagList
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetUserReadingListByTag(Guid id, string tag)
        {
            if (id == Guid.Empty || string.IsNullOrEmpty(tag))
            {
                return NotFound();
            }

            var repository = _unitOfWork.GetRepository<Article>() as ArticleRepository;
            var readingList = await repository.GetAllArticles().Where(article => article.Favourites.Any(favourite => favourite.UserId == id) &&
                                                                                 article.Tags.Any(z => z.Title == tag)).ToListAsync();

            return PartialView("~/Views/Shared/ReadingList/_ReadingListPartial.cshtml", readingList);
        }

        [HttpGet]
        public async Task<int> GetUserReadingListCount(Guid id)
        {
            var repository = _unitOfWork.GetRepository<Article>() as ArticleRepository;
            var readingList = await repository.GetAllArticles().Where(article => article.Favourites.Any(favourite => favourite.UserId == id)).ToListAsync();

            return readingList.Count;
        }
    }
}

src/Blog.Web/Views/User/GetUserReadingList.cshtml
@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager

@model ReadingListViewModel

@{
    ViewData["Title"] = "Reading List";
}

<div class="wrapper">
    <main class="blog-layout blog-layout--header-inside blog-layout--2-cols">
        @*  Header  *@
        <header class="blog-page-header flex">
            @*  Reading list (count)  *@
            <div class="flex justify-between items-center flex-1 mb-0">
                <h1 class="blog-title flex-1">Избранные статьи (@Model.Articles.Count())</h1>
            </div>
            @*  Search field  *@
            <fieldset class="flex justify-end pl-2 w-auto">
                <input id="searchbox" class="blog-textfield mb-0" type="text" placeholder="Поиск...">
            </fieldset>
        </header>
        @*  Sidebar  *@
        <div class="blog-layout__sidebar-left">
            <nav aria-label="Filter by tag">
                <ul class="list-none">
                    <li>
                        <a class="blog-link blog-link--block blog-link--current" asp-action="GetUserReadingList" asp-controller="User" asp-route-id="@Model.UserId">Все теги</a>
                    </li>
                    @foreach (var tag in Model.Tags)
                    {
                        <li>
                            <a class="tag blog-link blog-link--block" data-id="@Model.UserId" data-tag="@tag" asp-controller="User" asp-action="GetUserReadingListByTag">
                                #@tag
                            </a>
                        </li>
                    }
                </ul>
            </nav>
        </div>
        @*  Articles  *@
        <section class="blog-layout__content blog-card pb-4">
            @if (Model.Articles.Any())
            {
                @foreach (var article in Model.Articles)
                {
                    @*  Get username  *@
                    var user = await UserManager.GetUserNameAsync(article.User);

                    <article class="flex p-6 pb-2 pr-6">
                        @*  Avatar  *@
                        <a class="blog-avatar blog-avatar--l" asp-controller="User" asp-action="GetUserProfile" asp-route-id="@article.UserId">
                            <img class="blog-avatar__image" src="/img/avatars/@article.User.ImagePath">
                        </a>
                        @*  Article data  *@
                        <div class="flex-1 pl-2 pl-4">
                            @*  Title  *@
                            <a class="flex blog-link" asp-controller="Article" asp-action="Details" asp-route-id="@article.Id">
                                <h2 class="lh-tight fs-l fw-bold break-word">@article.Title</h2>
                            </a>
                            @*  Article info  *@
                            <p class="fs-s">
                                @*  Author  *@
                                <a class="blog-link fw-medium" asp-controller="User" asp-action="GetUserProfile" asp-route-id="@article.UserId">@user</a>
                                <span class="color-base-30"> • </span>
                                @*  Creation date / time to read  *@
                                <span class="color-base-60">
                                    @article.Date.ToLongDateString()
                                    <span class="color-base-30"> • </span>
                                    @Math.Ceiling((double)article.Text.Length / 1500) мин на чтение
                                </span>
                                @*  Tags  *@
                                <span>
                                    <span class="color-base-30"> • </span>
                                    @foreach (var tag in article.Tags)
                                    {
                                        <a class="blog-tag blog-tag--monochrome" asp-controller="Tag" asp-action="Details" asp-route-id="@tag.Id">
                                            <span class="blog-tag__prefix">#</span>@tag.Title
                                        </a>
                                    }
                                </span>
                            </p>
                        </div>
                        @*  Favourite button  *@
                        <div class="self-center">
                            @if (article.Favourites.Any(x => x.ArticleId == article.Id && x.UserId.ToString() == UserManager.GetUserId(User)))
                            {
                                <button class="c-btn c-btn--icon-alone reading-list" type="button" title="Save to reading list" aria-pressed="true" value="@article.Id">
                                    <svg class="crayons-icon c-btn__icon" focusable="false" width="24" height="24" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M6.75 4.5h10.5a.75.75 0 0 1 .75.75v14.357a.375.375 0 0 1-.575.318L12 16.523l-5.426 3.401A.375.375 0 0 1 6 19.607V5.25a.75.75 0 0 1 .75-.75z"></path>
                                    </svg>
                                </button>
                            }
                            else
                            {
                                <button class="c-btn c-btn--icon-alone reading-list" type="button" title="Save to reading list" aria-pressed="false" value="@article.Id">
                                    <svg class="crayons-icon c-btn__icon" focusable="false" width="24" height="24" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M6.75 4.5h10.5a.75.75 0 0 1 .75.75v14.357a.375.375 0 0 1-.575.318L12 16.523l-5.426 3.401A.375.375 0 0 1 6 19.607V5.25a.75.75 0 0 1 .75-.75zM16.5 6h-9v11.574l4.5-2.82 4.5 2.82V6z"></path>
                                    </svg>
                                </button>
                            }
                        </div>
                    </article>
                }
            }
            else
            {
                <section class="align-center p-9 py-10 color-base-80">
                    <h2 class="fw-bold fs-l">Список избранных статей пуст</h2>
                    <p class="color-base-60 pt-2">
                        Нажмите на
                        <span class="fw-bold">
                            значок закладки
                            <svg class="blog-icon mx-1" width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" role="img">
                                <path d="M5 2h14a1 1 0 011 1v19.143a.5.5 0 01-.766.424L12 18.03l-7.234 4.536A.5.5 0 014 22.143V3a1 1 0 011-1zm13 2H6v15.432l6-3.761 6 3.761V4z"></path>
                            </svg>
                        </span>
                        если хотите добавить статью в избранное.
                    </p>
                </section>
            }
        </section>
    </main>
</div>

@section scripts{
    <script>
        //Search

        let cards = document.querySelectorAll('article')

        function liveSearch() {
            let search_query = document.getElementById("searchbox").value;

            for (var i = 0; i < cards.length; i++) {
                if (cards[i].textContent.toLowerCase()
                    .includes(search_query.toLowerCase())) {
                    cards[i].classList.remove("hidden");
                } else {
                    cards[i].classList.add("hidden");
                }
            }
        }

        let typingTimer;
        let typeInterval = 500;
        let searchInput = document.getElementById('searchbox');

        searchInput.addEventListener('keyup', () => {
            clearTimeout(typingTimer);
            typingTimer = setTimeout(liveSearch, typeInterval);
        });
    </script>
}